### PR TITLE
update license

### PR DESCRIPTION
**Pull request by JaeseungYeom**
Updated license to the latest Flux framework's license.

### CODE REVIEW

**Comment by JaeseungYeom** [comment]
> /lib/dyad_stream_core.hpp

Thank for finding it. I will correct that.

**Comment by garlick** [comment]
Are you using the Flux process here where PRs must be merged by another team member?  If so, I'm happy to push the button when you are ready.

**Comment by JaeseungYeom** [comment]
> Are you using the Flux process here where PRs must be merged by another team member? If so, I'm happy to push the button when you are ready.

If that is the practice, please by all means. As of now, this code base needs a little more organization. We will continue to work on that. I was waiting for the response from IPO to make sure everything checks out. They think this is fine but also recommended to go through ESW.

**Comment by garlick** [comment]
Yes we've been using that practice and some others prescribed by  [this process](https://github.com/grondo/flux-framework-rfc/blob/master/spec_1.rst) which was forked from the [zeromq](https://zeromq.org/) project long ago. 

Feel free to cherry pick from there what works here.

I'll go ahead and merge this PR and if further license changes are needed, that can be another PR.

**Pull request merged**
