### PR TITLE
Hotfix: various build system fixes to support CI

### PR DESCRIPTION
**Pull request by ilumsden**
#49 made UCX an optional dependency. However, it did not make the UCX-based code in `dyad_dtl_init` and `dyad_dtl_finalize` conditionally compiled. As a result, if a user built DYAD without `--enable-ucx` and then set the DTL mode to `UCX`, failures would occur due to `dyad_dtl_init` and `dyad_dtl_finalize` trying to call the corresponding UCX DTL functions, which would not have been built.

This hotfix PR fixes this small, but important, bug.

### CODE REVIEW

**Comment by hariharan-devarajan** [comment]
Also, fix configure.ac

```
PKG_CHECK_VAR([UCX_LIBDIR],
    [ucx >= 1.6.0],
    [libdir],
    [],
    [AC_MSG_FAILURE([Could not find libdir for UCX])]
)
AS_IF([test "x$UCX_LIBDIR" = "x"],
    [AC_MSG_FAILURE([check_var succeeded, but value is incorrect])]
)
```

**Comment by hariharan-devarajan** [comment]
Also can u merge it with the CI PR to see if its fixed and do any other changes required for that.

**Comment by JaeseungYeom** [comment]
I will wait on the update for making sure to free dtl_handle in the finalization

**Comment by ilumsden** [comment]
@JaeseungYeom I've fixed the freeing of the DTL handle in `dyad_dtl_finalize`. I've also rebased my branch on the newest version of `main`.

**Pull request merged**
