### PR TITLE
Makes Core into Core and Client and Exposes Client API to Users

### PR DESCRIPTION
**Pull request by ilumsden**
This PR is based on feedback from #118. If we like it, it can supersede and replace #118.

This PR moves headers around and modifies the CMake to make DYAD's core and ctx libraries available to users. It also splits `dyad_core.h` and `dyad_structures.h` into multiple headers (an external header and an internal one) so that excess function definitions are not exposed to users. It also creates a new `dyad/core/dyad.h` header and `dyad_client` CMake target to refer to both libraries at once.

### CODE REVIEW

**Comment by ilumsden** [comment]
I rebased this PR on top of #116 for testing purposes. Please merge #116 before merging this PR.

**Comment by ilumsden** [comment]
I tested this using A4X, and it works as expected

**Comment by wangvsa** [comment]
@ilumsden  is this ready to review/merge? This one and #124 are big PRs and I'd like to merge them first if possible.

**Comment by ilumsden** [comment]
Yes. This PR is ready for review and merge.

**Pull request merged**
