### PR TITLE
Wrapper name change

### PR DESCRIPTION
**Pull request by JaeseungYeom**
Changing `libdyad_sync.so` to `dyad_wrapper.so`
This is basedon PR #22. Once it is merged, I will rebase this. That will leave only the change relevant to this visible.
TODO: Make sure the ECP tutorial uses the version it was created with using git tag

### CODE REVIEW

**Comment by ilumsden** [comment]
@JaeseungYeom #22 has been merged

**Comment by JaeseungYeom** [comment]
rebased

**Review by ilumsden — APPROVED** [review]
Looks good!

**Comment by ilumsden** [comment]
I've opened a PR to pin the version of DYAD in the ECP tutorial to v0.1.1: https://github.com/flux-framework/Tutorials/pull/16

Once that PR is merged, this PR should be OK to merge.

**Pull request merged**
